### ISSUE TITLE
responseViewPreview not working for json

### ISSUE THREAD

**Issue by jakoss** [AnWeber/vscode-httpyac#20] opened 2021-03-02 10:35 UTC
I have setting `"httpyac.responseViewPreview": true` and it's working fine for plain text response, but whenever the resulting type is application/json - the tab seems to be "normal" instead of preview (and it displays confirmation popup whenever i try to close it)

![image](https://user-images.githubusercontent.com/3933348/109636084-732c9f80-7b4b-11eb-998a-43899e818a24.png)

**Comment by AnWeber** [comment] 2021-03-02 19:08
The setting is passed directly to [showTextDocument](https://github.com/AnWeber/vscode-httpyac/blob/main/src/view/responseOutputProcessor.ts#L208). No further logic takes place. I'll have another read of [vscode api](https://code.visualstudio.com/api/references/vscode-api#TextDocumentShowOptions) on this, but I don't currently see any error. It doesn't work for me either, but I have preview disabled in general (not for the test)

**Comment by AnWeber** [comment] 2021-03-08 20:38
I have played again with the preview setting. It seems that this is only used when the file is saved and opened using vscode.uri. I could not understand the behavior that the preview mode works with text files. 
The thought now would be to save the files to a tmp folder and clean them up after closing. This would have the advantage that I could also set the filename, and thus improve the display.

**Comment by jakoss** [comment] 2021-03-08 21:22
Sounds reasonable for me. But any idea why this is only happening on application/json but not on text responses?

**Comment by AnWeber** [comment] 2021-03-08 21:28
Nope. Could not reproduce on any content-type. could you provide an example
and configured settings?

Jakub Syty <notifications@github.com> schrieb am Mo., 8. März 2021, 22:23:

**Comment by jakoss** [comment] 2021-03-09 06:11
Ok, I got enlightened.. It was not a matter of an content type. It was matter of empty response. If I get 204 from server the tab does not require confirmation to close it because it's just empty. Slow thinking on my part here..

**Comment by AnWeber** [comment] 2021-03-12 21:09
I have published a new version. With this version the preview should work correctly now. In viewMode preivew the response must be saved as a file, otherwise vscode does not allow the preview mode. If preview is generally switched off, the previous logic is used as fallback. But this can also be activated with setting `httpyac.responseViewMode`.

**Comment by jakoss** [comment] 2021-03-13 21:40
Works great, thanks!

**Closed** 2021-03-18 12:24 UTC
