### ISSUE TITLE
Error parsing json property with minus

### ISSUE THREAD

**Issue by rabestro** [AnWeber/vscode-httpyac#261] opened 2024-02-21 22:53 UTC
Source test:

```http
{{host}}/actuator/info

?? status == 200
?? body app exists
?? body git exists
?? body build exists
?? body os exists
?? body java exists
?? body java.version startsWith 17
?? body app.source-code endsWith pig-latin-rest
?? body app.source-code contains rabestro
```

### TestResults

✓: status == 200
✓: app exists
✓: git exists
✓: build exists
✓: os exists
✓: java exists
✓: java.version startsWith 17
✖: app.source-code endsWith pig-latin-rest (ReferenceError: code is not defined - Object.userJS (/Users/jegors/Projects/engx-advanced/pig-latin-rest/httpYac/actuator/server-info.http:2:70)
✖: app.source-code contains rabestro (ReferenceError: code is not defined - Object.userJS (/Users/jegors/Projects/engx-advanced/pig-latin-rest/httpYac/actuator/server-info.http:2:70)

**Comment by AnWeber** [comment] 2024-02-24 16:42
duplicate of AnWeber/httpyac#640

**Closed by AnWeber** 2024-02-24 16:42 UTC
